---
ldap_domain: edusmart.lan
ldap_base_dn: dc=edusmart,dc=lan
ldap_admin_dn: cn=admin,dc=edusmart,dc=lan
ldap_organization: EduSmart

ldap_tls_directory: /etc/ldap/tls
ldap_tls_private_key_path: /etc/ldap/tls/ldap-server.key
ldap_tls_certificate_path: /etc/ldap/tls/ldap-server.crt
ldap_tls_ca_certificate_path: /etc/ldap/tls/edusmart-root-ca.crt

# Pas de LDAP non chiffré sur le réseau.
ldap_slapd_services: "ldapi:/// ldaps:///"

ldap_primary_uri: ldaps://ldap.edusmart.lan

# Réplication OpenLDAP
ldap_database_dn: "olcDatabase={1}mdb,cn=config"
ldap_sync_dn: "cn=replicator,dc=edusmart,dc=lan"
ldap_sync_cn: replicator

ldap_provider_uri: ldaps://srv-prd-par-idm-001.edusmart.lan
ldap_replica_uri: ldaps://srv-prd-par-idm-002.edusmart.lan
ldap_replica_rid: "001"

# Arborescence LDAP POSIX
ldap_people_dn: "ou=People,dc=edusmart,dc=lan"
ldap_groups_dn: "ou=Groups,dc=edusmart,dc=lan"

ldap_users_group:
  cn: ldap-users
  dn: "cn=ldap-users,ou=Groups,dc=edusmart,dc=lan"
  gid_number: "20000"

ldap_test_user:
  uid: testldap
  dn: "uid=testldap,ou=People,dc=edusmart,dc=lan"
  given_name: Utilisateur
  surname: Test
  common_name: Utilisateur Test
  display_name: Utilisateur Test
  uid_number: "20001"
  gid_number: "20000"
  home_directory: /home/testldap
  login_shell: /bin/bash
  mail: testldap@edusmart.lan
