---
ldap_domain: edusmart.lan
ldap_base_dn: dc=edusmart,dc=lan
ldap_admin_dn: cn=admin,dc=edusmart,dc=lan
ldap_organization: EduSmart

ldap_tls_directory: /etc/ldap/tls
ldap_tls_private_key_path: /etc/ldap/tls/ldap-server.key
ldap_tls_certificate_path: /etc/ldap/tls/ldap-server.crt
ldap_tls_ca_certificate_path: /etc/ldap/tls/edusmart-root-ca.crt

# Pas de LDAP non chiffré sur le réseau.
ldap_slapd_services: "ldapi:/// ldaps:///"

ldap_primary_uri: ldaps://ldap.edusmart.lan
