---
postfix_myhostname: srv-prd-par-smtp-001.edusmart.lan
postfix_mydomain: edusmart.lan

postfix_relayhost: smtp.gmail.com
postfix_relayport: 587

postfix_admin_recipient: w.laurent@edusmart.lan

postfix_mynetworks:
  - 127.0.0.0/8
  - 10.10.50.11/32
  - 10.10.20.23/32

postfix_message_size_limit: 10485760

# Routage du domaine de messagerie interne
postfix_internal_mail_domain: edusmart.lan
postfix_internal_mail_server: 10.10.20.23
postfix_internal_mail_port: 25
