---
- name: Redémarrer journald
  ansible.builtin.systemd_service:
    name: systemd-journald
    state: restarted

- name: Redémarrer Chrony
  ansible.builtin.systemd_service:
    name: chrony
    state: restarted
