---
all:
  children:
    ansible_controllers:
      hosts:
        srv-prd-par-ans-001:
          ansible_host: 10.10.30.20

    linux_servers:
      children:
        idm_servers:
          hosts:
            srv-prd-par-idm-001:
              ansible_host: 10.10.20.21
              idm_role: primary

            srv-prd-par-idm-002:
              ansible_host: 10.10.20.22
              idm_role: replica

        mail_servers:
          hosts:
            srv-prd-par-mail-001:
              ansible_host: 10.10.20.23

        smtp_relays:
          hosts:
            srv-prd-par-smtp-001:
              ansible_host: 10.10.20.24

        docker_hosts:
          hosts:
            srv-prd-par-dkr-001:
              ansible_host: 10.10.50.11

  vars:
    ansible_user: svc_ansible
    ansible_ssh_private_key_file: /home/eds_admin/.ssh/id_ed25519_ansible
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
