---
linux_admin_group: eds_admins

linux_human_admins:
  - username: r.sibbille
    full_name: Ruben Sibbille
    ssh_key_file: r.sibbille.pub

  - username: s.mousset
    full_name: Sacha Mousset
    ssh_key_file: s.mousset.pub

linux_exceptional_admin:
  username: eds_admin
  enabled: true

linux_ansible_service_account:
  username: svc_ansible

linux_breakglass_account:
  username: eds_breakglass
  enabled: true
  password_hash: "{{ vault_breakglass_password_hash | default('') }}"
