---
- name: Finaliser le durcissement SSH EduSmart
  hosts: ansible_controllers
  become: true
  gather_facts: false

  tasks:
    - name: Appliquer la configuration SSH finale
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        insertbefore: BOF
        marker: "# {mark} ANSIBLE MANAGED BLOCK - EDUSMART SSH"
        backup: true
        block: |
          PermitRootLogin no
          PubkeyAuthentication yes
          PasswordAuthentication no
          KbdInteractiveAuthentication no
          AuthenticationMethods publickey
          PermitEmptyPasswords no
          MaxAuthTries 3
          LoginGraceTime 30
          X11Forwarding no
          AllowAgentForwarding no
          AllowTcpForwarding no
          PermitTunnel no
          ClientAliveInterval 300
          ClientAliveCountMax 2
          AllowUsers eds_admin svc_ansible r.sibbille s.mousset
          DenyUsers eds_breakglass
        validate: "/usr/sbin/sshd -t -f %s"
      notify: Recharger SSH

  handlers:
    - name: Recharger SSH
      ansible.builtin.systemd_service:
        name: ssh
        state: reloaded
