---
- name: Déployer la supervision Docker EduSmart
  hosts: docker_hosts
  become: true
  gather_facts: true

  vars_files:
    - ../inventories/production/vault/smtp.yml

  roles:
    - role: monitoring_stack
