---
- name: Configurer le fournisseur de réplication OpenLDAP
  hosts: idm_servers
  become: true
  gather_facts: false

  vars_files:
    - ../inventories/production/vault/ldap.yml

  roles:
    - role: openldap_replication_provider
