---
- name: Générer les certificats LDAP des serveurs IDM
  hosts: idm_servers
  serial: 1
  become: true
  gather_facts: false

  vars_files:
    - ../inventories/production/vault/pki.yml

  roles:
    - role: pki_ldap_server
