---
- name: Déployer le relais SMTP EduSmart
  hosts: smtp_relays
  become: true
  gather_facts: true

  vars_files:
    - ../inventories/production/vault/smtp.yml

  roles:
    - role: postfix_relay
